service: twentyfour-hour-video
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

custom:
  upload-bucket: upload-video-bucket-ea
  transcode-bucket: transcoded-video-bucket-ea
  transcode-video-role: arn:aws:iam::117771065608:role/transcode-video 
  media-endpoint: https://4l8tgbpha.mediaconvert.us-west-2.amazonaws.com
  media-role: arn:aws:iam::117771065608:role/media-convert-role

functions:
  transcode-video:
    handler: transcode-video/index.handler
    role: ${self:custom.transcode-video-role}
    package:
      individually: true
    environment:
      MEDIA_ENDPOINT: ${self:custom.media-endpoint}
      MEDIA_ROLE: ${self:custom.media-role}
      TRANSCODED_VIDEO_BUCKET: ${slef:custom.transcode-bucket}
    events:
      - s3: ${self:custom.upload-bucket}